version: "3"
services:
  openvpn:
    image: aristarkh87/docker-openvpn
    ports:
      - "1194:1194/udp"
    volumes:
      - ./ovpn-data:/etc/openvpn
    cap_add:
    - NET_ADMIN
    restart: always
